services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: oneclickvirt-web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certs:/etc/nginx/certs
    restart: always
    networks:
      - default

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: oneclickvirt-api
    ports:
      - "8890:8890"
    volumes:
      - ./data/app/:/app/storage
      - ./data/config:/app/config
      - ./server/config.yaml:/app/config.yaml:rw
    restart: always
    networks:
      - default

  mysql:
    image: mariadb:10.11
    container_name: oneclickvirt-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD:  "yes"
        MYSQL_DATABASE: oneclickvirt
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data/mysql:/var/lib/mysql
      - ./deploy/my.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      - default

volumes:
  mysql_data:

networks:
  default:
    driver: bridge